# Generated by Django 5.2.17 on 2026-09-18 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=150)),
                ('date_earned', models.CharField(blank=True, max_length=40)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification / Achievement',
                'verbose_name_plural': 'Certifications / Achievements',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, default='Present', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list, for example Django, Python, Bootstrap', max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True, verbose_name='Live demo URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='T. Vimala', max_length=120)),
                ('title', models.CharField(default='Python Developer', max_length=120)),
                ('tagline', models.CharField(default='Building clean, reliable web applications with Python and Django.', max_length=255)),
                ('about', models.TextField(default='I am a B.Tech student with a strong interest in Information Technology, Python, Django, web development, and software engineering. I enjoy turning ideas into well-structured applications and continuously improving my skills through projects, practice, and certifications.')),
                ('location', models.CharField(blank=True, default='India', max_length=120)),
                ('email', models.EmailField(default='vimala@example.com', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com/your-github')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/in/your-linkedin')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, help_text='Upload a PDF resume. If empty, the default static resume path is used.', null=True, upload_to='resume/')),
                ('resume_static_path', models.CharField(default='portfolio/files/T_Vimala_Resume.pdf', help_text='Static file path used when no uploaded resume is set.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('proficiency', models.PositiveSmallIntegerField(default=75, help_text='Skill level from 1 to 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(blank=True, default='Core', max_length=80)),
                ('icon', models.CharField(blank=True, default='bi-code-slash', help_text='Bootstrap Icons class, for example bi-filetype-py', max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
